### ISSUE TITLE
Crashes d3 when loaded

### ISSUE THREAD

**Issue by bekonowicz** [dkaoster/d3-parliament-chart#13]
I load d3 v7 and d3 parliament chart right after it. Then functions and objects from d3 are gone. I get, for example, 

`Uncaught TypeError: d3.json is not a function`

**Comment by dkaoster** [comment]
@bekonowicz Thanks for the report, getting a fix issued now.

**Comment by dkaoster** [comment]
fixed in https://github.com/dkaoster/d3-parliament-chart/releases/tag/0.0.6

**Comment by bekonowicz** [comment]
Thanks a lot, mate!
